"""creating new tables

Revision ID: 9ea939765351
Revises: 2cbc237a3f88
Create Date: 2025-02-04 17:09:19.968366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from src.models import Base

# revision identifiers, used by Alembic.
revision: str = '9ea939765351'
down_revision: Union[str, None] = '2cbc237a3f88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())
    print("All tables have been created.")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_choices_id'), table_name='choices')
    op.drop_table('choices')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_quizzes_title'), table_name='quizzes')
    op.drop_index(op.f('ix_quizzes_subject'), table_name='quizzes')
    op.drop_index(op.f('ix_quizzes_id'), table_name='quizzes')
    op.drop_index(op.f('ix_quizzes_genre'), table_name='quizzes')
    op.drop_table('quizzes')
    # ### end Alembic commands ###
