"""added generes

Revision ID: c42546b16f04
Revises: 8a92d93c5b5b
Create Date: 2025-01-31 15:57:27.138735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c42546b16f04'
down_revision: Union[str, None] = '8a92d93c5b5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('genre', sa.String(), nullable=True))
    op.create_index(op.f('ix_quizzes_genre'), 'quizzes', ['genre'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quizzes_genre'), table_name='quizzes')
    op.drop_column('quizzes', 'genre')
    # ### end Alembic commands ###
