"""Added attempts in table

Revision ID: ed679c210512
Revises: 9ea939765351
Create Date: 2025-02-13 01:27:04.276014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed679c210512'
down_revision: Union[str, None] = '9ea939765351'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_attempts_id'), 'quiz_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_quiz_id'), 'quiz_attempts', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_user_id'), 'quiz_attempts', ['user_id'], unique=False)
    op.drop_constraint('choices_question_id_fkey', 'choices', type_='foreignkey')
    op.create_foreign_key(None, 'choices', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_questions_quiz_id'), 'questions', ['quiz_id'], unique=False)
    op.drop_constraint('questions_quiz_id_fkey', 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'quizzes', ['quiz_id'], ['id'], ondelete='CASCADE')
    op.add_column('quizzes', sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficultylevel'), nullable=True))
    op.add_column('quizzes', sa.Column('duration', sa.Integer(), nullable=True))
    op.drop_index('ix_quizzes_title', table_name='quizzes')
    op.create_index(op.f('ix_quizzes_title'), 'quizzes', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quizzes_title'), table_name='quizzes')
    op.create_index('ix_quizzes_title', 'quizzes', ['title'], unique=False)
    op.drop_column('quizzes', 'duration')
    op.drop_column('quizzes', 'difficulty')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key('questions_quiz_id_fkey', 'questions', 'quizzes', ['quiz_id'], ['id'])
    op.drop_index(op.f('ix_questions_quiz_id'), table_name='questions')
    op.drop_constraint(None, 'choices', type_='foreignkey')
    op.create_foreign_key('choices_question_id_fkey', 'choices', 'questions', ['question_id'], ['id'])
    op.drop_index(op.f('ix_quiz_attempts_user_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_quiz_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_id'), table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    # ### end Alembic commands ###
